spring:
  redis:
    host: localhost
    port: 6379
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:XE
    username: system_admin
    password: secret

jwt:
   validity: 300

server:
  servlet:
    session:
      timeout: 10m
