spring:
  redis:
    host: localhost
    port: 6379
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:XE
    username: system_admin
    password: secret
  session:
    store-type: redis
    timeout: 10m  # Session timeout set to 10 minutes

server:
  servlet:
    context-path: /api/system

jwt:
   validity: 300
