version: '3.8'
services:
  oracle:
    build:
      context: oracle
    image: gvenzl/oracle-xe
    container_name: oracle
    restart: unless-stopped
    environment:
      - DB_SID=XE
      - DB_PASSWD=secret
      - ORACLE_PASSWORD=secret
    ports:
      - '1521:1521'
    volumes:
      - 'oracle_data:/opt/oracle/oradata'
      - './init-script.sql:/docker-entrypoint-initdb.d/init-script.sql'
  redis:
    image: bitnami/redis
    container_name: redis
    restart: unless-stopped
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    ports:
      - '6379:6379'
    volumes:
      - 'redis_data:/bitnami/redis/data'
  sftp:
    image: atmoz/sftp
    container_name: sftp
    restart: unless-stopped
    ports:
      - '900:22'
    command: sftp-user:secret::documents
volumes:
  oracle_data:
    driver: local
  redis_data:
    driver: local