CREATE TABLE Course_Schedule (
    schedule_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    course_id NUMBER NOT NULL,
    schedule BLOB NOT NULL,
    FOREIGN KEY (course_id) REFERENCES Course(course_id)
);